### ISSUE TITLE
Installation instructions (suggestion)

### ISSUE THREAD

**Issue by jbrucker** [bankkeez/dailigram#75]
This is not a bug, but Installation instructions in README suggest
user to create a directory named `.venv`.  In a bash shell, directory names
beginning with a "." are hidden by default. Your instructions work, 
but user might not notice his own `.venv` directory.

Typically, its named `venv` (no ".") or `env`. 
If you change this, also add it to .gitignore.

**Comment by kimvcp** [comment]
Ok now it's fixed
