### ISSUE TITLE
After sign in, The webpage shows Interval Server Error 

### ISSUE THREAD

**Issue by ffaiip** [bankkeez/dailigram#78]
I try to sign in with long username, then the webpage shows Interval Server Error.
After that I can not access your website ever.

![image](https://user-images.githubusercontent.com/32285945/49365591-cbc92400-f719-11e8-9424-210a2d2c0701.png)

**Comment by bankkeez** [comment]
Sorry for inconvinience, we have fix that so registering a username letter will not exceed 20 characters.
