### ISSUE TITLE
Can't re create older name after get alert request

### ISSUE THREAD

**Issue by darmonlyone** [bankkeez/dailigram#80]
When i try create new diary and its cause error. So i retry to create it again with same name but its said this name already exit.

**Comment by kimvcp** [comment]
What is the error when trying to create new diary.

**Comment by Kittinske15** [comment]
Please try again for sureness, We didn't see the way of causing this error.

**Comment by bankkeez** [comment]
The app seems to work normally so I am going to close the issue.
