### ISSUE TITLE
Title field show web cache from other website after click.

### ISSUE THREAD

**Issue by NokKbl** [bankkeez/dailigram#85]
I didn't use this web before but when I pressed create and click a text field to put Title, this web show the cache text from other web (which don't know where) as show in the picture which is not good.

<img src="http://drive.google.com/uc?export=view&id=1Pk7aQqxFvjLvpM9hVrA0XkzGUnXuipo_">

**Comment by kimvcp** [comment]
We didn't expect that to happen. We will fixed it soon
